USE [master]
GO

/****** Object:  Database [TIENDA.2]    Script Date: 27/05/2022 5:43:06 ******/
CREATE DATABASE [TIENDA.2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TIENDA.2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TIENDA.2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TIENDA.2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TIENDA.2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TIENDA.2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TIENDA.2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TIENDA.2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TIENDA.2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TIENDA.2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TIENDA.2] SET ARITHABORT OFF 
GO

ALTER DATABASE [TIENDA.2] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TIENDA.2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TIENDA.2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TIENDA.2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TIENDA.2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TIENDA.2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TIENDA.2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TIENDA.2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TIENDA.2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TIENDA.2] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TIENDA.2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TIENDA.2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TIENDA.2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TIENDA.2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TIENDA.2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TIENDA.2] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [TIENDA.2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TIENDA.2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TIENDA.2] SET  MULTI_USER 
GO

ALTER DATABASE [TIENDA.2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TIENDA.2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TIENDA.2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TIENDA.2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TIENDA.2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TIENDA.2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TIENDA.2] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TIENDA.2] SET  READ_WRITE 
GO

